# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: sonr

hooks:
  before:
    - export RELEASE_DATE="$(date +%Y).$(date +%V).$(date +%u)"
    - echo "Release date is $RELEASE_DATE"


builds:
  - id: motr
    main: ./cmd/vault/main.go
    binary: app
    goos:
      - js
    goarch:
      - wasm

release:
  github:
    owner: onsonr
    name: motr
  name_template: '{{ .Tag }} | {{ .Env.RELEASE_DATE }}'
  draft: false
  replace_existing_draft: true
  replace_existing_artifacts: true
  extra_files:
    - glob: ./README*

announce:
  telegram:
    enabled: true
    chat_id: -1002222617755
