# https://taskfile.dev

version: "3"

tasks:
  sqlc-gen:
    dir: internal
    cmds:
      - sqlc generate
    silent: true

  templ-gen:
    cmds:
      - templ generate
    silent: true

  pkl-gen:
    cmds:
      - pkl-gen-go internal/pkl/App.pkl
    silent: true
